"""Policies, traces and expected verdicts as one TLA+ module, for DogwoodSemantics to judge.

A CASE is a policy set, one event trace, and what the decisions in it should be. Many cases go into
one generated module, so a whole corpus -- or a whole decision table -- costs one TLC run rather
than one each:

    case ──┬── policies ──> TLA+ policy data ──┐
           ├── trace ─────> TLA+ trace data ───┼──> DogwoodSemantics: Agree / Decide / Determining
           └── oracle ─────────────────────────┘

Two ways to ask. `check` model-checks `Agree`, which is all-or-nothing: TLC stops at the first case
that disagrees with its oracle, which is what a regression corpus wants. `evaluate` asks for the
model's VERDICT at every decision, and which rules determined it, in one evaluation -- which is what
a decision table wants, where every disagreement is worth reporting, not only the first.

Moved here from `tests/strands/dogwood_differential.py`, which built it first, so that the checker
and the MCP server can use it. Nothing in `src/` imports from `tests/`.
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

from .emit import policy_seq, tla_record, tla_scalar, tla_value
from .tlc import parse_tla_value, run_eval, run_tlc

SPECS = Path(__file__).resolve().parents[2] / "specs" / "policy" / "TemporalPolicy"


def case_record(name: str, policies: list[dict], trace: list[dict],
                oracle: dict[int, bool],
                rules: dict[int, set[int]] | None = None) -> str:
    """One case as a TLA+ record.

    `rules` is the per-decision set of DETERMINING policy indices, 1-based to match the spec's
    policy sequence. It is optional because the unit corpus records no attribution; omitted, it
    becomes the empty function and the attribution check passes vacuously.
    """
    events = ", ".join(
        f'[time |-> {e["time"]}, action |-> "{e["action"]}", kind |-> "{e["kind"]}", '
        f'input |-> {tla_record(e["input"])}, output |-> {tla_record(e["output"])}, '
        f'principal |-> {tla_scalar(e["principal"])}, resource |-> {tla_scalar(e["resource"])}, '
        f'session |-> {tla_scalar(e["session"])}, '
        f'pins |-> {tla_record(e["pins"])}, '
        f'isDecision |-> {tla_value(e["decision"])}]'
        for e in trace)

    pols = policy_seq(policies, indent="", sep=", ")

    orc = " @@ ".join(f"{i} :> {tla_value(v)}" for i, v in sorted(oracle.items()))

    # `<< >>` is the empty function, which is what "this corpus records no attribution" means.
    # An empty SET for one decision is different and is a real claim: nothing matched, so the
    # deny is by default.
    rul = (" @@ ".join(f"{i} :> {{{', '.join(str(r) for r in sorted(rs))}}}"
                       for i, rs in sorted(rules.items()))
           if rules else "")

    # The domain a bound variable of non-Timepoint type ranges over: every scalar the trace
    # actually contains. Finite, so TLC can enumerate the assignments.
    #
    # PRINCIPALS AND RESOURCES BELONG IN IT, not just payload fields. `callerPrincipal: p` binds a
    # FRESH variable to the event's caller -- `exists (pr: Drupe::OAuthUser). ...` correlating two
    # predicates on the same principal without naming which. With the domain built from payloads
    # alone, no candidate value could ever equal a principal, so such a predicate never matched
    # and corpus case 1121 disagreed.
    vals = sorted({v for e in trace for rec in (e["input"], e["output"]) for v in rec.values()}
                  | {e["principal"] for e in trace} | {e["resource"] for e in trace},
                  key=lambda x: (type(x).__name__, x))
    values = ", ".join(tla_scalar(v) for v in vals)

    return (f'    [name |-> "{name}", trace |-> <<{events}>>, '
            f'policies |-> <<{pols}>>, oracle |-> ({orc}), '
            f'rules |-> {f"({rul})" if rul else "<< >>"}, '
            f'values |-> {{{values}}}]')


# The model's verdict, and the determining rules, at every decision of every case -- one value, so
# a whole table is one evaluation. Rules are 1-based policy indices.
#
# Each case's verdicts are a SET of <<decision, allowed, rules>>, not a function. A function over
# decisions 1, 3, 5 prints as `1 :> ... @@ 3 :> ...`, which is not a value our reader models; a set
# of tuples prints as plain braces and angle brackets, which it does.
VERDICTS = """
Verdicts == [c \\in DOMAIN Cases |->
    { << d,
         S!Decide(Cases[c].trace, Cases[c].policies, d, Cases[c].values),
         S!Determining(Cases[c].trace, Cases[c].policies, d, Cases[c].values) >>
      : d \\in DOMAIN Cases[c].oracle }]
"""


def generate_module(cases: list[str], extra: str = "") -> str:
    """One module holding every case, so the corpus costs one TLC run rather than one each."""
    return """\\* GENERATED by Anchor (src/translator/cases.py) -- do not edit.
\\* Policies and traces, each with the verdicts its decisions should reach.
------------------------- MODULE DogwoodCases -------------------------
EXTENDS Integers, Sequences, TLC

\\* The empty attribute record. An event with no `input:` carries no fields at all,
\\* which is different from carrying fields that are empty.
EmptyRec == [f \\in {} |-> ""]

Cases ==
  <<
""" + ",\n".join(cases) + """
  >>

S == INSTANCE DogwoodSemantics

VARIABLE done
Init == done = FALSE
Next == UNCHANGED done
Spec == Init /\\ [][Next]_done

Agree == S!Agree
""" + extra + """
=============================================================================
"""


CONFIG = """\
SPECIFICATION Spec
CHECK_DEADLOCK FALSE
INVARIANT Agree
"""


def _workdir(tmp: Path, module_text: str) -> None:
    (tmp / "DogwoodCases.tla").write_text(module_text, encoding="utf-8")
    (tmp / "DogwoodCases.cfg").write_text(CONFIG, encoding="utf-8")
    shutil.copyfile(SPECS / "DogwoodSemantics.tla", tmp / "DogwoodSemantics.tla")


def check(module_text: str) -> tuple[bool, str]:
    """Model-check `Agree`: (every case agreed with its oracle, TLC's output)."""
    with tempfile.TemporaryDirectory(prefix="anchor-dogwood-") as tmp:
        work = Path(tmp)
        _workdir(work, module_text)
        return run_tlc("DogwoodCases", work, work)


def evaluate(cases: list[str]) -> list[dict[int, tuple[bool, set[int]]]]:
    """The model's verdict and determining rules at every decision, case by case.

    One TLC evaluation for the lot. Raises RuntimeError with TLC's output if no value came back --
    an evaluation that printed nothing is a failure, never an empty answer.
    """
    with tempfile.TemporaryDirectory(prefix="anchor-cases-") as tmp:
        work = Path(tmp)
        _workdir(work, generate_module(cases, VERDICTS))
        ok, out = run_eval("Verdicts", "DogwoodCases", work, spec="Spec")
    if not ok:
        raise RuntimeError(f"the model's verdicts could not be evaluated:\n{out[-2000:]}")
    value, _ = parse_tla_value(out)
    if len(value) != len(cases):
        raise RuntimeError(f"expected verdicts for {len(cases)} case(s), got {len(value)}")
    return [{int(d): (bool(allowed), set(rules)) for d, allowed, rules in per_case}
            for per_case in value]


def collect_disagreements(output: str) -> list[str]:
    """Each disagreement as one line, gathered from the tuple TLC wraps across several.

    The Assert carries the case, the decision index and both verdicts. Matching only the line the
    word "DISAGREEMENT" lands on throws all of that away and leaves `<< "DISAGREEMENT",`.
    """
    lines, out, i = output.splitlines(), [], 0
    while i < len(lines):
        if "DISAGREEMENT" not in lines[i]:
            i += 1
            continue
        parts = []
        while i < len(lines):
            parts.append(lines[i].strip())
            if ">>" in lines[i]:
                break
            i += 1
        out.append(" ".join(parts).replace('"DISAGREEMENT",', "").replace("<<", "").strip())
        i += 1
    return out
