\* GENERATED by src/translator/policy_module.py from business_hours.dw -- do not edit.
\*
\* Translated by the parser that agrees with the Dogwood reference implementation on 919 recorded
\* corpus pairs. Vacuity.tla checks THESE records, so what is model-checked is the policy as
\* written rather than as paraphrased.
---------------------------- MODULE PolicyUnderTest ----------------------------
EXTENDS Integers, Sequences

Source == "business_hours.dw"

\* The vocabulary is lifted from the policy text: only actions, event kinds and input/output
\* fields some condition actually reads are modelled. A policy that joins on nothing costs nothing.
Actions      == {"issue_refund"}
Kinds        == {"request"}
InputFields  == {"systemNowTime"}
OutputFields == {}
DecisionKind == "request"

\* Each field's own domain: every literal the policy compares it against, plus one it does not,
\* so that both matching and not-matching are reachable. Fields move independently, which is
\* what lets a policy reading several of them be explored at all.
InputDomain  == [systemNowTime |-> {[k |-> "n", v |-> 32399999], [k |-> "n", v |-> 32400000], [k |-> "n", v |-> 61200000], [k |-> "n", v |-> 61200001]}]
OutputDomain == [f \in {} |-> {}]
AllValues    == {[k |-> "n", v |-> 32399999], [k |-> "n", v |-> 32400000], [k |-> "n", v |-> 61200000], [k |-> "n", v |-> 61200001]}

\* The fields a universal pin partitions on. Empty means global-trace semantics -- which is the
\* `unpinned` preset, NOT the shipped default. Vacuity.tla gives a session two callers when this
\* is non-empty, so a partition has something to exclude.
PinKeys == {"principal"}

\* ---- for a property module extending this one --------------------------------------------
\* Scalars are TAGGED with their kind so TLC refuses a cross-kind comparison rather than quietly
\* answering one. Write `Num(22)`, never `22`.
\* An address is FOUR OCTETS, never a 32-bit number: TLC works in Java ints and stops at
\* 2147483647, so 208.4.4.0 -- 3489924096 -- is not a value it can hold.
Addr(a, b, c, d) == [k |-> "a", v |-> <<a, b, c, d>>]
Str(x)  == [k |-> "s", v |-> x]
Num(x)  == [k |-> "n", v |-> x]
Bool(x) == [k |-> "b", v |-> x]
Anon    == Str("caller")

NoFields == [f \in {} |-> Str("")]

\* ONE EVENT AT A CHOSEN TIME AND KIND, which is what a claim about a SESSION is built from.
\*
\* `time` IS IN SECONDS. The evaluator compares it against a window width directly --
\* `t - trace[i].time <= window` -- so a claim about a 15-minute window needs events 900 apart,
\* not two. This is the one thing that catches people out, because the built-in questions
\* explore sessions whose events are one second apart: a long window can never age out there,
\* and only a hand-built trace can put a decision on the far side of one.
Ev(action, kind, input, output, time) ==
    [time      |-> time,
     action    |-> action,
     kind      |-> kind,
     input     |-> input,
     output    |-> output,
     principal |-> Anon,
     resource  |-> Anon,
     session   |-> Anon,
     pins      |-> [k \in PinKeys |-> Anon]]

\* One request, at time 1, with no outputs -- the shorthand for a per-request claim, where
\* "what does this policy decide for this request" needs no session at all.
Request(action, input) == Ev(action, DecisionKind, input, NoFields, 1)

\* NOTE WHAT IS ABSENT: there is no `Inputs`. The request space derivable here comes from the
\* literals THIS POLICY names, so a claim about a value it never mentions would range over no
\* such request and hold vacuously. State the requests your claim is about.

Policies ==
  <<
    [effect |-> "permit", actions |-> {"issue_refund"}, cond |-> [op |-> "and", args |-> <<[op |-> "term", args |-> <<>>, term |-> [op |-> "at", window |-> 0, atom |-> [op |-> "cmp", pred |-> [action |-> "", kind |-> "", binds |-> <<>>], var |-> "", args |-> <<>>, field |-> "systemNowTime", cmp |-> ">=", value |-> [k |-> "n", v |-> 32400000], other |-> "", pattern |-> <<>>, net |-> <<>>, prefix |-> 0], left |-> [op |-> "cmp", pred |-> [action |-> "", kind |-> "", binds |-> <<>>], var |-> "", args |-> <<>>, field |-> "systemNowTime", cmp |-> ">=", value |-> [k |-> "n", v |-> 32400000], other |-> "", pattern |-> <<>>, net |-> <<>>, prefix |-> 0], leftNeg |-> FALSE, keys |-> <<"principal">>]], [op |-> "term", args |-> <<>>, term |-> [op |-> "at", window |-> 0, atom |-> [op |-> "cmp", pred |-> [action |-> "", kind |-> "", binds |-> <<>>], var |-> "", args |-> <<>>, field |-> "systemNowTime", cmp |-> "<=", value |-> [k |-> "n", v |-> 61200000], other |-> "", pattern |-> <<>>, net |-> <<>>, prefix |-> 0], left |-> [op |-> "cmp", pred |-> [action |-> "", kind |-> "", binds |-> <<>>], var |-> "", args |-> <<>>, field |-> "systemNowTime", cmp |-> "<=", value |-> [k |-> "n", v |-> 61200000], other |-> "", pattern |-> <<>>, net |-> <<>>, prefix |-> 0], leftNeg |-> FALSE, keys |-> <<"principal">>]]>>, term |-> [op |-> "formerly", window |-> 0, atom |-> [op |-> "pred", pred |-> [action |-> "", kind |-> "", binds |-> <<>>], var |-> "", args |-> <<>>, field |-> "", cmp |-> "", value |-> [k |-> "s", v |-> ""], other |-> "", pattern |-> <<>>, net |-> <<>>, prefix |-> 0], left |-> [op |-> "pred", pred |-> [action |-> "", kind |-> "", binds |-> <<>>], var |-> "", args |-> <<>>, field |-> "", cmp |-> "", value |-> [k |-> "s", v |-> ""], other |-> "", pattern |-> <<>>, net |-> <<>>, prefix |-> 0], leftNeg |-> FALSE, keys |-> <<>>]]]
  >>

Other == Policies

=============================================================================
